In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
insurance_data = pd.read_csv("insurance.csv")
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## One Hot Encoding

### Seperate/Distructure a column based on its value (different value = different column)

- `X:` _DataFrame_ - data
- `columns:` _Array_ - which columns you want to seperate/distructure
- `drop_first:`_Boolean_ - To remove one redudant variable. If seperated columns are 4 then you can keep only 3 column. because 4th column will be complement of other 3 columns
- `dtype:` _data type(int, float, boolean)_ - whats the type of value in the column you want

In [3]:
X = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]


X = pd.get_dummies(X, columns=['region'], drop_first=True, dtype=int)
X["sex"] = X["sex"].map({"female":0, "male":1})
X["smoker"] = X["smoker"].map(lambda s: 1 if s=="yes" else 0)
X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,0,0,1
1,18,1,33.770,1,0,0,1,0
2,28,1,33.000,3,0,0,1,0
3,33,1,22.705,0,0,1,0,0
4,32,1,28.880,0,0,1,0,0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2_score(y_test, y_pred) #r squared value of 0.75, which is pretty good for a linear regression model

0.7835929767120724

## Interaction Features

In [8]:
X["age_smoker"] = X["age"] * X["smoker"]
X["bmi_smoker"] = X["bmi"] * X["smoker"]

X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,0,27.900,0,1,0,0,1,19,27.9
1,18,1,33.770,1,0,0,1,0,0,0.0
2,28,1,33.000,3,0,0,1,0,0,0.0
3,33,1,22.705,0,0,1,0,0,0,0.0
4,32,1,28.880,0,0,1,0,0,0,0.0

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2_test = r2_score(y_test, y_pred)
print(f"R-squared on test set: {r2_test:.4f}")

R-squared on test set: 0.8652

## Overfit & Underfit model

- `Underfit:` r2 training score is low and r2 testing is also low
  - **High Bias** - Error from wrong assumptions
  - **Low Variance** - Sensitivity to data change. Model predictions stay consistent but inaccurate across different datasets
- `Overfit:`r2 training >> r2 testing
  - **Low Bias** - Model fits the training data very closely with minimal assumptions
  - **High Variance** - Model predictions change drastically when applied to new datasets

In [16]:
y_train_pred = model.predict(X_train)
r2_train = r2_score(y_train, y_train_pred)
print(f"R-squared on training set: {r2_train:.4f}")
print(f"R-squared on test set: {r2_test:.4f}")

R-squared on training set: 0.8341
R-squared on test set: 0.8652