In [4]:
import pandas as pd

In [15]:
info = {
    "name":["Adam", "Eve","Bob","Ibrahim","Mahamud","Shafiq"],
    "age":[24,34,32,45,12, 23],
    "gpa":[2.3,2.3,3.4,4.3,5.4,5.6]
}

In [16]:
df = pd.DataFrame(info)

In [17]:
df

      name  age  gpa
0     Adam   24  2.3
1      Eve   34  2.3
2      Bob   32  3.4
3  Ibrahim   45  4.3
4  Mahamud   12  5.4
5   Shafiq   23  5.6

In [18]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [19]:
df.columns

Index(['name', 'age', 'gpa'], dtype='object')

In [40]:
data = [
    ["Adam",34],
    ["Eve",24],
    ["Eva",54],
]
df = pd.DataFrame(data, columns=["Name","Age"])

In [41]:
df

   Name  Age
0  Adam   34
1   Eve   24
2   Eva   54

In [43]:
import numpy as np
np_array = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_array,columns=["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6